name: BWM Build (22-slot generalszh.exe)

on:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  build-bwm-zerohour:
    uses: ./.github/workflows/build-toolchain.yml
    with:
      game: "GeneralsMD"
      preset: "vc6-weekly"
      tools: false
      extras: false
    secrets: inherit